Setup required packages with bindep
python-jenkins fails to build without the kerberose packages and those
packages are not included in our xenial images.  Use bindep to
configure the required minimum set of required packages.

build error:
  building 'kerberos' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes
   -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong
   -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/base64.c
   -o build/temp.linux-x86_64-2.7/src/base64.o sh: 1: krb5-config: not found
  x86_64-linux-gnu-gcc: error: sh:: No such file or directory
  x86_64-linux-gnu-gcc: error: 1:: No such file or directory
  x86_64-linux-gnu-gcc: error: krb5-config:: No such file or directory
  x86_64-linux-gnu-gcc: error: not: No such file or directory
  x86_64-linux-gnu-gcc: error: found: No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for kerberos

Change-Id: Iad6e10ef6ef05e0b5c6db08dbb97b2c3a3e42a30