testtools requires unittest2
It seems like testtools requires unittest2 now so we need to add it to
the requirements.

Error I got when ran 'tox -epy27' in fresh env:

  Running setup.py install for testtools
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/khaido/PycharmProjects/python-jenkins/.tox/py27/build/testtools/setup.py", line 10, in <module>
        import testtools
      File "testtools/__init__.py", line 69, in <module>
        from testtools.testcase import (
      File "testtools/testcase.py", line 28, in <module>
        import unittest2 as unittest
    ImportError: No module named unittest2
    Complete output from command /Users/khaido/PycharmProjects/python-jenkins/.tox/py27/bin/python -c "import setuptools;__file__='/Users/khaido/PycharmProjects/python-jenkins/.tox/py27/build/testtools/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/5d/t1_1wr6n1_gg_jwnl8qx2fqm0000gn/T/pip-Lya9W8-record/install-record.txt --single-version-externally-managed --install-headers /Users/khaido/PycharmProjects/python-jenkins/.tox/py27/include/site/python2.7:
    Traceback (most recent call last):

Change-Id: I060f0ff36cec915c86cfaf6277af89fb8d9ea58e