Disable requests_kerberos in tests
When requests_kerberos is not set to None, there are two authenticators
in Jenkins._auths. In that case, _maybe_add_auth checks which one is
suitable with jenkins_open.

The mocked jenkins server (NullServer) does not respond with anything,
in test tests.test_jenkins_sockets.JenkinsRequestTimeoutTests.test_jenkins_open_timeout
hence the timeout is hit in _maybe_add_auth. That results in
JenkinsException instead of TimeoutException expected by the test.

Traceback from
tests.test_jenkins_sockets.JenkinsRequestTimeoutTests.test_jenkins_open_timeout:

  Traceback (most recent call last):
    File "tests/test_jenkins_sockets.py", line 31, in test_jenkins_open_timeout
      j.jenkins_open(request, add_crumb=False)
    File "jenkins/__init__.py", line 533, in jenkins_open
      return self.jenkins_request(req, add_crumb, resolve_auth).text
    File "jenkins/__init__.py", line 547, in jenkins_request
      self._maybe_add_auth()
    File "jenkins/__init__.py", line 384, in _maybe_add_auth
      % '\n'.join(failures))
  jenkins.JenkinsException: Unable to authenticate with any scheme:
  auth(kerberos) Error in request: HTTPConnectionPool(host='127.0.0.1', port=33921): Read timed out. (read timeout=0.1)
  auth(anonymous) Error in request: HTTPConnectionPool(host='127.0.0.1', port=33921): Read timed out. (read timeout=0.1)

Change-Id: Id20343f6fc368bbd7001dbfa87138eef946480cf